# Generated by Django 3.2.3 on 2021-05-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210525_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconnection',
            name='button_url',
            field=models.CharField(max_length=500),
        ),
    ]
